version: "3"

services:
  scylla-node:
    image: scylladb/scylla:4.6.2
    restart: always
    command: --smp 1 --memory 250M --overprovisioned 1 --authenticator PasswordAuthenticator
    volumes:
      - ../build/package/docker/scylla/initial-load.sh:/initial-load.sh:Z
      - ../build/package/docker/scylla/initial-load.conf:/etc/supervisord.conf.d/initial-load.conf:Z
      - ../build/package/docker/scylla/cql:/home/cql:Z
    ports:
      - "9042:9042"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9094,OUTSIDE://127.0.0.1:9092
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    restart: unless-stopped

  schemaregistry:
    image: confluentinc/cp-schema-registry:7.2.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8086:8086"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:9094'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8086

  ui:
    image: provectuslabs/kafka-ui
    container_name: kafkaui
    depends_on:
      - zookeeper
      - kafka
      - schemaregistry
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8086

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9000:9090
    volumes:
      - ../build/package/docker/prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml