// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IKafkaProducer is an autogenerated mock type for the IKafkaProducer type
type IKafkaProducer struct {
	mock.Mock
}

// Send provides a mock function with given fields: msg, topic, subject
func (_m *IKafkaProducer) Send(msg interface{}, topic string, subject string) error {
	ret := _m.Called(msg, topic, subject)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, string) error); ok {
		r0 = rf(msg, topic, subject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIKafkaProducer interface {
	mock.TestingT
	Cleanup(func())
}

// NewIKafkaProducer creates a new instance of IKafkaProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIKafkaProducer(t mockConstructorTestingTNewIKafkaProducer) *IKafkaProducer {
	mock := &IKafkaProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
