APP_NAME: "account-producer-service"
SERVER_HOST: "0.0.0.0:1002"
HEALTH_SERVER_HOST: "0.0.0.0:1003"

KAFKA_CLIENT_ID: "account-producer-service"
KAFKA_HOSTS: "localhost:9092"
KAFKA_SCHEMA_REGISTRY_HOST: "http://localhost:8081"
KAFKA_ACKS: "all"
KAFKA_TIMEOUT: 10
KAFKA_USE_AUTEHNTICATION: false
KAFKA_ENABLE_TLS: true
KAFKA_SASL_MECHANISM: "SCRAM-SHA-512"
KAFKA_USER: "kafka"
KAFKA_PASSWORD: "kafka"
KAFKA_SCHEMA_REGISTRY_USER: ""
KAFKA_SCHEMA_REGISTRY_PASSWORD: ""
KAFKA_ENABLE_EVENTS: true
KAFKA_MAX_MESSAGE_BYTES: 0
KAFKA_RETRY_MAX: 0
KAFKA_DLQ_TOPIC: "account_createorupdate_dlq account_delete_dlq account_get_dlq account_get_response_dlq"
KAFKA_CONSUMER_TOPIC: "account_createorupdate account_delete account_get account_get_response"
KAFKA_CONSUMER_GROUP: "account-producer-service"

VIA_CEP_URL: "https://viacep.com.br/ws/"
VIA_CEP_MAX_RETRIES_HTTP_REQUEST: 3
VIA_CEP_MAX_FAILURE_RATIO: 0.6
VIA_CEP_NAME: "HTTP GET"