APP_NAME: "account-producer-service"
SERVER_HOST: "0.0.0.0:8080"
HEALTH_SERVER_HOST: "0.0.0.0:8081"

DATABASE_USER: "cassandra"
DATEBASE_PASSWORD: "cassandra"
DATEBASE_KEYSPACE: "account_consumer_service"
DATEBASE_HOST: "localhost"
DATEBASE_PORT: 9042
DATEBASE_CONNECTION_RETRY_TIME: 5
DATEBASE_RETRY_MIN: 1
DATEBASE_RETRY_MAX: 10
DATEBASE_NUM_RETRIES: 5
DATEBASE_CLUSTER_TIMEOUT: 5

KAFKA_CLIENT_ID: "account-producer-service"    
KAFKA_HOSTS: "localhost:9092"
KAFKA_USE_AUTHENTICATION: "false"  
KAFKA_SASL_MECHANISM: "SCRAM-SHA-512"
KAFKA_ENABLE_TLS: "true"
KAFKA_SCHEMA_REGISTRY_HOST: "http://localhost:8086"
KAFKA_CREATE_OR_UPDATE_TOPIC_NAME: "account_createorupdate"
KAFKA_DELETE_TOPIC_NAME: "account_delete"

VIA_CEP_URL: "https://viacep.com.br/ws/"
VIA_CEP_MAX_RETRIES_HTTP_REQUEST: 3
VIA_CEP_MAX_FAILURE_RATIO: 0.6
VIA_CEP_NAME: "HTTP GET"